alter table UCOFIRSTTASK_PRODUCT add constraint FK_UCOFIRSTTASK_PRODUCT_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID);
create index IDX_UCOFIRSTTASK_PRODUCT_ON_IMAGE_FILE on UCOFIRSTTASK_PRODUCT (IMAGE_FILE_ID);
