alter table UCOFIRSTTASK_ACCOUNT add constraint FK_UCOFIRSTTASK_ACCOUNT_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID);
create index IDX_UCOFIRSTTASK_ACCOUNT_ON_IMAGE_FILE on UCOFIRSTTASK_ACCOUNT (IMAGE_FILE_ID);
