-- begin UCOFIRSTTASK_CONTACT
alter table UCOFIRSTTASK_CONTACT add constraint FK_UCOFIRSTTASK_CONTACT_ON_ACCOUNT foreign key (ACCOUNT_ID) references UCOFIRSTTASK_ACCOUNT(ID)^
create index IDX_UCOFIRSTTASK_CONTACT_ON_ACCOUNT on UCOFIRSTTASK_CONTACT (ACCOUNT_ID)^
-- end UCOFIRSTTASK_CONTACT
-- begin UCOFIRSTTASK_ACCOUNT
alter table UCOFIRSTTASK_ACCOUNT add constraint FK_UCOFIRSTTASK_ACCOUNT_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
create index IDX_UCOFIRSTTASK_ACCOUNT_ON_IMAGE_FILE on UCOFIRSTTASK_ACCOUNT (IMAGE_FILE_ID)^
-- end UCOFIRSTTASK_ACCOUNT
