-- begin UCOFIRSTTASK_CONTACT
alter table UCOFIRSTTASK_CONTACT add constraint FK_UCOFIRSTTASK_CONTACT_ON_ACCOUNT foreign key (ACCOUNT_ID) references UCOFIRSTTASK_ACCOUNT(ID)^
create index IDX_UCOFIRSTTASK_CONTACT_ON_ACCOUNT on UCOFIRSTTASK_CONTACT (ACCOUNT_ID)^
-- end UCOFIRSTTASK_CONTACT
-- begin UCOFIRSTTASK_ACCOUNT
alter table UCOFIRSTTASK_ACCOUNT add constraint FK_UCOFIRSTTASK_ACCOUNT_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
create index IDX_UCOFIRSTTASK_ACCOUNT_ON_IMAGE_FILE on UCOFIRSTTASK_ACCOUNT (IMAGE_FILE_ID)^
-- end UCOFIRSTTASK_ACCOUNT
-- begin UCOFIRSTTASK_ORDER_LINE
alter table UCOFIRSTTASK_ORDER_LINE add constraint FK_UCOFIRSTTASK_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references UCOFIRSTTASK_ORDER(ID)^
alter table UCOFIRSTTASK_ORDER_LINE add constraint FK_UCOFIRSTTASK_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references UCOFIRSTTASK_PRODUCT(ID)^
create index IDX_UCOFIRSTTASK_ORDER_LINE_ON_ORDER on UCOFIRSTTASK_ORDER_LINE (ORDER_ID)^
create index IDX_UCOFIRSTTASK_ORDER_LINE_ON_PRODUCT on UCOFIRSTTASK_ORDER_LINE (PRODUCT_ID)^
-- end UCOFIRSTTASK_ORDER_LINE
-- begin UCOFIRSTTASK_ORDER
alter table UCOFIRSTTASK_ORDER add constraint FK_UCOFIRSTTASK_ORDER_ON_ACCOUNT foreign key (ACCOUNT_ID) references UCOFIRSTTASK_ACCOUNT(ID)^
create index IDX_UCOFIRSTTASK_ORDER_ON_ACCOUNT on UCOFIRSTTASK_ORDER (ACCOUNT_ID)^
-- end UCOFIRSTTASK_ORDER
-- begin UCOFIRSTTASK_PRODUCT
alter table UCOFIRSTTASK_PRODUCT add constraint FK_UCOFIRSTTASK_PRODUCT_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
create index IDX_UCOFIRSTTASK_PRODUCT_ON_IMAGE_FILE on UCOFIRSTTASK_PRODUCT (IMAGE_FILE_ID)^
-- end UCOFIRSTTASK_PRODUCT
